apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-web-app
  namespace: my-web-app
spec:
  ingressClassName: nginx
  rules:
  - hosts: my-web-app.jackjj.store
    http:
      paths:
      - backend:
          service:
            name: my-web-app
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - my-web-app.jackjj.store
    secretName: my-web-app-tls

